language: python
python:
  - "2.7"
  - "3.3"
install:
  - pip install argparse
  - pip install nose flake8
# For now install ament_package from git
  - git clone https://github.com/ament/ament_package.git
  - cd ament_package
  - python setup.py install
  - cd ..
script:
  - python setup.py nosetests -s
notifications:
  email: false
